// Code generated by pgxstores. DO NOT EDIT.
// This file is only generated if it doesn't already exist.
// Once created, you can customize this file freely - it will not be overwritten.

package taskspgxstore

import (
	"github.com/jrazmi/envoker/sdk/logger"
	"github.com/jrazmi/envoker/infrastructure/postgresdb"
)

// Store provides database access for Task
type Store struct {
	log  *logger.Logger
	pool *postgresdb.Pool
}

// NewStore creates a new Task store
func NewStore(log *logger.Logger, pool *postgresdb.Pool) *Store {
	return &Store{
		log:  log,
		pool: pool,
	}
}
