// Code generated by pgxstores. DO NOT EDIT.
// This file contains CRUD operations for Task.

package taskspgxstore

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"strings"
	"time"
	"encoding/json"

	"github.com/jackc/pgx/v5"
	"github.com/jrazmi/envoker/core/repositories/tasksrepo"
	"github.com/jrazmi/envoker/core/scaffolding/fop"
	"github.com/jrazmi/envoker/infrastructure/postgresdb"
)

// Create inserts a new Task
func (s *Store) Create(ctx context.Context, input tasksrepo.CreateTask) (tasksrepo.Task, error) {
	// PK is in Create struct - use value from input
	query := `INSERT INTO public.tasks (task_id, processing_status, task_type, metadata, priority, max_retries, retry_count, error_message, processing_time_ms, last_run_at) VALUES (@task_id, @processing_status, @task_type, @metadata, @priority, @max_retries, @retry_count, @error_message, @processing_time_ms, @last_run_at) RETURNING task_id, processing_status, created_at, updated_at, task_type, metadata, priority, max_retries, retry_count, error_message, processing_time_ms, last_run_at`

	args := pgx.NamedArgs{
		"task_id": input.TaskId,
		"processing_status": input.ProcessingStatus,
		"task_type": input.TaskType,
		"metadata": input.Metadata,
		"priority": input.Priority,
		"max_retries": input.MaxRetries,
		"retry_count": input.RetryCount,
		"error_message": input.ErrorMessage,
		"processing_time_ms": input.ProcessingTimeMs,
		"last_run_at": input.LastRunAt,
	}

	rows, err := s.pool.Query(ctx, query, args)
	if err != nil {
		return tasksrepo.Task{}, postgresdb.HandlePgError(err)
	}
	defer rows.Close()

	record, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[tasksrepo.Task])
	if err != nil {
		return tasksrepo.Task{}, postgresdb.HandlePgError(err)
	}

	return record, nil
}

// Get retrieves a single Task by ID
func (s *Store) Get(ctx context.Context, taskId string) (tasksrepo.Task, error) {
	query := `SELECT task_id, processing_status, created_at, updated_at, task_type, metadata, priority, max_retries, retry_count, error_message, processing_time_ms, last_run_at FROM public.tasks WHERE task_id = @taskId`

	args := pgx.NamedArgs{
		"taskId": taskId,
	}

	rows, err := s.pool.Query(ctx, query, args)
	if err != nil {
		return tasksrepo.Task{}, postgresdb.HandlePgError(err)
	}
	defer rows.Close()

	record, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[tasksrepo.Task])
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return tasksrepo.Task{}, fmt.Errorf("Task not found")
		}
		return tasksrepo.Task{}, postgresdb.HandlePgError(err)
	}

	return record, nil
}

// Update modifies an existing Task
func (s *Store) Update(ctx context.Context, taskId string, input tasksrepo.UpdateTask) error {
	buf := bytes.NewBufferString("UPDATE public.tasks SET ")
	args := pgx.NamedArgs{
		"taskId": taskId,
	}
	var fields []string
	if input.ProcessingStatus != nil {
		fields = append(fields, "processing_status = @processing_status")
		args["processing_status"] = *input.ProcessingStatus
	}
	if input.TaskType != nil {
		fields = append(fields, "task_type = @task_type")
		args["task_type"] = *input.TaskType
	}
	if input.Metadata != nil {
		fields = append(fields, "metadata = @metadata")
		args["metadata"] = *input.Metadata
	}
	if input.Priority != nil {
		fields = append(fields, "priority = @priority")
		args["priority"] = *input.Priority
	}
	if input.MaxRetries != nil {
		fields = append(fields, "max_retries = @max_retries")
		args["max_retries"] = *input.MaxRetries
	}
	if input.RetryCount != nil {
		fields = append(fields, "retry_count = @retry_count")
		args["retry_count"] = *input.RetryCount
	}
	if input.ErrorMessage != nil {
		fields = append(fields, "error_message = @error_message")
		args["error_message"] = *input.ErrorMessage
	}
	if input.ProcessingTimeMs != nil {
		fields = append(fields, "processing_time_ms = @processing_time_ms")
		args["processing_time_ms"] = *input.ProcessingTimeMs
	}
	if input.LastRunAt != nil {
		fields = append(fields, "last_run_at = @last_run_at")
		args["last_run_at"] = *input.LastRunAt
	}

	// Always update the updated_at field
	now := time.Now().UTC()
	if input.UpdatedAt != nil {
		args["updated_at"] = *input.UpdatedAt
	} else {
		args["updated_at"] = now
	}
	fields = append(fields, "updated_at = @updated_at")

	// If no fields to update besides updated_at, return early
	if len(fields) == 1 {
		return fmt.Errorf("no fields to update")
	}

	// Join fields and complete the query
	buf.WriteString(strings.Join(fields, ", "))
	buf.WriteString(" WHERE task_id = @taskId")

	query := buf.String()
	s.log.DebugContext(ctx, "update Task", "query", query, "taskId", taskId)

	result, err := s.pool.Exec(ctx, query, args)
	if err != nil {
		return postgresdb.HandlePgError(err)
	}

	if result.RowsAffected() == 0 {
		return fmt.Errorf("Task not found")
	}

	return nil
}

// Delete removes a Task by ID
func (s *Store) Delete(ctx context.Context, taskId string) error {
	query := `DELETE FROM public.tasks WHERE task_id = @taskId`

	args := pgx.NamedArgs{
		"taskId": taskId,
	}

	result, err := s.pool.Exec(ctx, query, args)
	if err != nil {
		return postgresdb.HandlePgError(err)
	}

	if result.RowsAffected() == 0 {
		return fmt.Errorf("Task not found")
	}

	return nil
}

// List retrieves Task records with filtering, ordering, and cursor pagination
func (s *Store) List(ctx context.Context, filter tasksrepo.TaskFilter, orderBy fop.By, page fop.PageStringCursor, forPrevious bool) ([]tasksrepo.Task, error) {
	data := pgx.NamedArgs{}

	// Start building the query
	buf := bytes.NewBufferString(`
		SELECT
			task_id,
			processing_status,
			created_at,
			updated_at,
			task_type,
			metadata,
			priority,
			max_retries,
			retry_count,
			error_message,
			processing_time_ms,
			last_run_at
		FROM
			public.tasks`)

	// Apply filters
	s.applyFilter(filter, data, buf)

	// Setup configuration for string cursor pagination
	cursorConfig := postgresdb.StringCursorConfig{
		Cursor:     page.Cursor,
		OrderField: orderByFields[orderBy.Field],
		PKField:    "task_id",
		TableName:  "tasks",
		Direction:  orderBy.Direction,
		Limit:      page.Limit,
	}

	// Apply cursor pagination
	if page.Cursor != "" {
		err := postgresdb.ApplyStringCursorPagination[time.Time](buf, data, cursorConfig, forPrevious)
		if err != nil {
			return nil, fmt.Errorf("cursorpagination: %s", err)
		}
	}

	// Add ordering
	err := postgresdb.AddOrderByClause(buf, cursorConfig.OrderField, cursorConfig.PKField, cursorConfig.Direction, forPrevious)
	if err != nil {
		return nil, fmt.Errorf("order: %w", err)
	}

	// Add limit
	postgresdb.AddLimitClause(cursorConfig.Limit, data, buf)

	// Execute the query
	query := buf.String()
	s.log.DebugContext(ctx, "list Task", "query", query)

	rows, err := s.pool.Query(ctx, query, data)
	if err != nil {
		return nil, postgresdb.HandlePgError(err)
	}
	defer rows.Close()

	entities, err := pgx.CollectRows(rows, pgx.RowToStructByName[tasksrepo.Task])
	if err != nil {
		return nil, postgresdb.HandlePgError(err)
	}

	// If we were getting previous page, reverse the results back to correct order
	if forPrevious && len(entities) > 0 {
		for i, j := 0, len(entities)-1; i < j; i, j = i+1, j-1 {
			entities[i], entities[j] = entities[j], entities[i]
		}
	}

	return entities, nil
}
