// Code generated by bridgegen. DO NOT EDIT.
// This file is only generated if it doesn't already exist.
// Once created, you can customize this file freely - it will not be overwritten.

package tasksrepobridge

import "github.com/jrazmi/envoker/core/repositories/tasksrepo"

// bridge provides HTTP handlers for Task operations
type bridge struct {
	taskRepository *tasksrepo.Repository
}

// newBridge creates a new Task bridge
func newBridge(taskRepository *tasksrepo.Repository) *bridge {
	return &bridge{
		taskRepository: taskRepository,
	}
}
