// Code generated by bridgegen. DO NOT EDIT.
// This file is only generated if it doesn't already exist.
// Once created, you can customize this file freely - it will not be overwritten.

package schemamigrationsrepobridge

import "github.com/jrazmi/envoker/core/repositories/schemamigrationsrepo"

// bridge provides HTTP handlers for SchemaMigration operations
type bridge struct {
	schemaMigrationRepository *schemamigrationsrepo.Repository
}

// newBridge creates a new SchemaMigration bridge
func newBridge(schemaMigrationRepository *schemamigrationsrepo.Repository) *bridge {
	return &bridge{
		schemaMigrationRepository: schemaMigrationRepository,
	}
}
