services:
  postgres:
    image: postgres:17-alpine
    container_name: envoker-postgres
    restart: always
    command: postgres -c ssl=off
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-envoker}
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - envoker-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-envoker}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  # redis:
  #   image: redis:7-alpine
  #   container_name: envoker-redis
  #   restart: always
  #   command: redis-server --appendonly yes
  #   volumes:
  #     - ./data/redis-data:/data
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - envoker-network
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

networks:
  envoker-network:
    driver: bridge
