package repositorygen

// RepoTemplate is the template for repo.go (generated only if doesn't exist)
const RepoTemplate = `// Code generated by repositorygen. DO NOT EDIT.
// This file is only generated if it doesn't already exist.
// Once created, you can customize this file freely - it will not be overwritten.

package {{.PackageName}}

import (
	"github.com/jrazmi/envoker/sdk/logger"
)

// Storer defines the complete data storage interface for {{.EntityName}}
// It embeds GeneratedStorer (from repo_gen.go) which contains all auto-generated methods.
// Add your custom storage methods here as needed.
type Storer interface {
	GeneratedStorer

	// Add custom methods below this line:
	// Example:
	// GetPendingTasksForWorker(ctx context.Context, workerID string) ([]{{.EntityName}}, error)
}

// Repository provides access to {{.EntityNameLower}} storage
type Repository struct {
	log    *logger.Logger
	storer Storer
}

// NewRepository creates a new {{.EntityName}} repository
func NewRepository(log *logger.Logger, storer Storer) *Repository {
	return &Repository{
		log:    log,
		storer: storer,
	}
}
`
