package repositorygen

// RepoFopGenTemplate is the template for fop_gen.go in repository layer
const RepoFopGenTemplate = `// Code generated by repositorygen. DO NOT EDIT.
// This file contains filtering, ordering, and pagination helpers for {{.EntityName}}.

package {{.PackageName}}

import (
	"time"

	"github.com/jrazmi/envoker/core/scaffolding/fop"
)

// OrderBy constants for sorting
const (
	OrderByPK        = "{{.PKColumn}}"
	OrderByCreatedAt = "created_at"
	OrderByUpdatedAt = "updated_at"
{{- range .Columns}}
{{- if and (ne .Name "created_at") (ne .Name "updated_at") (not .IsPrimaryKey)}}
	OrderBy{{ToPascalCase .Name}} = "{{.Name}}"
{{- end}}
{{- end}}
)

// DefaultOrderBy specifies the default sort order
var DefaultOrderBy = fop.NewBy(OrderByCreatedAt, fop.DESC)

// {{.EntityName}}Cursor for cursor-based pagination
type {{.EntityName}}Cursor = fop.Cursor[{{.PKGoType}}, time.Time]

// Decode{{.EntityName}}Cursor decodes a cursor token
func Decode{{.EntityName}}Cursor(token string) (*{{.EntityName}}Cursor, error) {
	return fop.DecodeCursor[{{.PKGoType}}, time.Time](token)
}

// Encode{{.EntityName}}Cursor encodes a cursor for pagination
func Encode{{.EntityName}}Cursor(createdAt time.Time, {{.PKParamName}} {{.PKGoType}}) (string, error) {
	cursor := {{.EntityName}}Cursor{
		OrderValue: createdAt,
		PK:         {{.PKParamName}},
	}
	return cursor.Encode()
}

// {{.EntityName}}Filter holds the available fields a query can be filtered on
type {{.EntityName}}Filter struct {
	SearchTerm *string ` + "`" + `json:"search_term,omitempty"` + "`" + ` // Search across text fields
{{- range .Columns}}
{{- if eq .Name "created_at"}}
	CreatedAtBefore *time.Time ` + "`" + `json:"created_at_before,omitempty"` + "`" + ` // Filter by created_at < value
	CreatedAtAfter  *time.Time ` + "`" + `json:"created_at_after,omitempty"` + "`" + ` // Filter by created_at > value
{{- else if eq .Name "updated_at"}}
	UpdatedAtBefore *time.Time ` + "`" + `json:"updated_at_before,omitempty"` + "`" + ` // Filter by updated_at < value
	UpdatedAtAfter  *time.Time ` + "`" + `json:"updated_at_after,omitempty"` + "`" + ` // Filter by updated_at > value
{{- else if and (not .IsPrimaryKey) (not (Contains .GoType "json.RawMessage"))}}
	{{ToPascalCase .Name}} *{{TrimPrefix .GoType "*"}} ` + "`" + `json:"{{.Name}},omitempty"` + "`" + ` // Filter by {{.Name}}
{{- end}}
{{- end}}
}
`
