package bridgegen

const BridgeTemplate = `// Code generated by bridgegen. DO NOT EDIT.

package {{.PackageName}}

import "{{.ModulePath}}/core/repositories/{{.RepoPackage}}"

type bridge struct {
	{{.EntityNameLower}}Repository *{{.RepoPackage}}.Repository
}

func newBridge({{.EntityNameLower}}Repository *{{.RepoPackage}}.Repository) *bridge {
	return &bridge{
		{{.EntityNameLower}}Repository: {{.EntityNameLower}}Repository,
	}
}
`
