package bridgegen

// BridgeInitTemplate is the template for bridge.go (generated only if doesn't exist)
const BridgeInitTemplate = `// Code generated by bridgegen. DO NOT EDIT.
// This file is only generated if it doesn't already exist.
// Once created, you can customize this file freely - it will not be overwritten.

package {{.BridgePackage}}

import "{{.ModulePath}}/core/repositories/{{.RepoPackage}}"

// bridge provides HTTP handlers for {{.Entity}} operations
type bridge struct {
	{{.EntityNameLower}}Repository *{{.RepoPackage}}.Repository
}

// newBridge creates a new {{.Entity}} bridge
func newBridge({{.EntityNameLower}}Repository *{{.RepoPackage}}.Repository) *bridge {
	return &bridge{
		{{.EntityNameLower}}Repository: {{.EntityNameLower}}Repository,
	}
}
`
