// Code generated by repositorygen. DO NOT EDIT.
// This file contains the Repository method implementations for SchemaMigration.

package schemamigrationsrepo

import (
	"context"
	"fmt"

	"github.com/jrazmi/envoker/core/scaffolding/fop"
)

// GeneratedStorer defines the auto-generated storage operations for SchemaMigration
// This interface is regenerated on every schema change. To add custom methods,
// embed this interface in your Storer interface in repo.go (which is not overwritten).
type GeneratedStorer interface {
	// Create inserts a new schemaMigration
	Create(ctx context.Context, input CreateSchemaMigration) (SchemaMigration, error)

	// Get retrieves a schemaMigration by its ID
	Get(ctx context.Context, version string) (SchemaMigration, error)

	// Update modifies an existing schemaMigration
	Update(ctx context.Context, version string, input UpdateSchemaMigration) error

	// Delete removes a schemaMigration by its ID
	Delete(ctx context.Context, version string) error

	// List retrieves SchemaMigrations with filters, ordering, and pagination
	List(ctx context.Context, filter SchemaMigrationFilter, orderBy fop.By, page fop.PageStringCursor, forPrevious bool) ([]SchemaMigration, error)
}

// Create inserts a new schemaMigration
func (r *Repository) Create(ctx context.Context, input CreateSchemaMigration) (SchemaMigration, error) {
	entity, err := r.storer.Create(ctx, input)
	if err != nil {
		return SchemaMigration{}, fmt.Errorf("create schemaMigration: %w", err)
	}
	return entity, nil
}

// Get retrieves a schemaMigration by its ID
func (r *Repository) Get(ctx context.Context, version string) (SchemaMigration, error) {
	entity, err := r.storer.Get(ctx, version)
	if err != nil {
		return SchemaMigration{}, fmt.Errorf("get schemaMigration[%v]: %w", version, err)
	}
	return entity, nil
}

// Update modifies an existing schemaMigration
func (r *Repository) Update(ctx context.Context, version string, input UpdateSchemaMigration) error {
	if err := r.storer.Update(ctx, version, input); err != nil {
		return fmt.Errorf("update schemaMigration[%v]: %w", version, err)
	}
	return nil
}

// Delete removes a schemaMigration by its ID
func (r *Repository) Delete(ctx context.Context, version string) error {
	if err := r.storer.Delete(ctx, version); err != nil {
		return fmt.Errorf("delete schemaMigration[%v]: %w", version, err)
	}
	return nil
}

// List retrieves SchemaMigrations with filters, ordering, and pagination
func (r *Repository) List(ctx context.Context, filter SchemaMigrationFilter, order fop.By, page fop.PageStringCursor) ([]SchemaMigration, fop.Pagination, error) {
	// Request one more record than needed to check for next page
	listPage := fop.PageStringCursor{
		Limit:  page.Limit + 1,
		Cursor: page.Cursor,
	}

	// Fetch one more record than requested to determine if there's a next page
	records, err := r.storer.List(ctx, filter, order, listPage, false)
	if err != nil {
		return nil, fop.Pagination{}, fmt.Errorf("query: %w", err)
	}

	returnableRecords := records
	nextCursor := ""

	// If we have more records than the limit, trim the list and set next cursor
	if len(records) > page.Limit {
		returnableRecords = records[:page.Limit]
		lastRecord := returnableRecords[len(returnableRecords)-1]
		nextCursor, err = EncodeSchemaMigrationCursor(lastRecord.CreatedAt, lastRecord.Version)
		if err != nil {
			return nil, fop.Pagination{}, fmt.Errorf("encode next cursor: %w", err)
		}
	}

	pagination := fop.Pagination{
		HasPrev:        false,
		Limit:          page.Limit,
		PreviousCursor: "",
		NextCursor:     nextCursor,
		PageTotal:      len(returnableRecords),
	}

	// Check if there's a previous page
	if page.Cursor != "" {
		prevRecords, err := r.storer.List(ctx, filter, order, page, true)
		if err == nil && len(prevRecords) > 0 {
			pagination.HasPrev = true
			if len(prevRecords) == page.Limit {
				// we are re-reversing the order in the storage layer so we should start with the first item instead of the last
				firstRecord := prevRecords[0]
				pagination.PreviousCursor, err = EncodeSchemaMigrationCursor(firstRecord.CreatedAt, firstRecord.Version)
				if err != nil {
					return nil, fop.Pagination{}, fmt.Errorf("encode prev cursor: %w", err)
				}
			}
		}
	}

	return returnableRecords, pagination, nil
}
